2020-2021/informatic/SemestrWork/SemestrovkaV2/SemestrovkaV2/SemestrovkaV2/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SemestrovkaV2.DataAccess.Abstract;
using SemestrovkaV2.DbModels;
using SemestrovkaV2.Email;
using SemestrovkaV2.Models;
using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SemestrovkaV2.Controllers
{
    public class CartController : Controller
    {
        private readonly ISneakerRepository sneakerRepository;

        public CartController(ISneakerRepository sneakerRepository)
        {
            this.sneakerRepository = sneakerRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var cart = GetCart();

            return View(new CartViewModel
            {
                Cart = cart,
                Sneakers = cart.Lines.ToList(),
                TotalPrice = cart.ComputeTotalPrice()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int id)
        {
            Sneaker s = sneakerRepository.FindById(id);
            if (s != null)
            {
                var sneaker = SneakerDetailInfo.SneakerFromDbModel(s);
                var cart = GetCart();
                cart.AddItem(sneaker);
                UpdateCart(cart);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int id)
        {
            Sneaker s = sneakerRepository.FindById(id);
            if (s != null)
            {
                var sneaker = SneakerDetailInfo.SneakerFromDbModel(s);
                var cart = GetCart();
                cart.RemoveLine(sneaker);
                UpdateCart(cart);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveOne(int id)
        {
            Sneaker s = sneakerRepository.FindById(id);
            if (s != null)
            {
                var sneaker = SneakerDetailInfo.SneakerFromDbModel(s);
                var cart = GetCart();
                cart.Remove(sneaker, 1);
                UpdateCart(cart);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrderAsync(string name, string email, string phoneNumber)
        {
            EmailService emailService = new EmailService();
            var customerEmailTheme = "Your order in SneakerShop";
            StringBuilder emailText = new StringBuilder();
            emailText.Append("You have ordered sneakers:\n");
            foreach (var line in GetCart().Lines)
            {
                emailText
                    .Append("- Name: ")
                    .Append(line.Sneaker.Name)
                    .Append("; Price: ")
                    .Append(line.Sneaker.Price)
                    .Append("; Quantity: ")
                    .Append(line.Quantity)
                    .Append("\n");
            }

            await emailService.SendEmailAsync(email, customerEmailTheme, emailText.ToString());

            var sellerEmailAddress = "victoria20011005@gmail.com";
            var sellerEmailTheme = "New order";
            emailText.Clear();
            emailText
                .Append("Customer ")
                .Append(name)
                .Append(" with email - ")
                .Append(email)
                .Append(" and phone number ")
                .Append(phoneNumber)
                .Append("have ordered these sneakers:\n");
            foreach (var line in GetCart().Lines)
            {
                emailText
                    .Append("- Name: ")
                    .Append(line.Sneaker.Name)
                    .Append("; Price: ")
                    .Append(line.Sneaker.Price)
                    .Append("; Quantity: ")
                    .Append(line.Quantity)
                    .Append("\n");
            }
            await emailService.SendEmailAsync(sellerEmailAddress, sellerEmailTheme, emailText.ToString());

            var cart = GetCart();
            cart.Clear();
            UpdateCart(cart);

            return RedirectToAction("Index");
        }


        private CartModel GetCart()
        {
            var serializedCart = HttpContext.Session.GetString("cart");

            if (serializedCart != null)
            {
                var deserializedCart = Newtonsoft.Json.JsonConvert.DeserializeObject<CartModel>(serializedCart);

                if (deserializedCart != null)
                {
                    return deserializedCart;
                }
            }
            var cart = new CartModel();
            HttpContext.Session.SetString(
                "cart",
                Newtonsoft.Json.JsonConvert.SerializeObject(cart));
            return cart;
        }

        private void UpdateCart(CartModel cart)
        {
            HttpContext.Session.SetString(
                "cart",
                Newtonsoft.Json.JsonConvert.SerializeObject(cart));
        }

    }
}

2020-2021/informatic/SemestrWork/SemestrovkaV2/SemestrovkaV2/SemestrovkaV2/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SemestrovkaV2.DataAccess.Abstract;
using SemestrovkaV2.DbModels;
using SemestrovkaV2.Models;

namespace SemestrovkaV2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISneakerRepository sneakerRepository;

        public HomeController(ISneakerRepository sneakerRepository)
        {
            this.sneakerRepository = sneakerRepository;
        }

        public IActionResult Index()
        {
            var allSneakers = this.sneakerRepository.List();

            return View(new SneakerListViewModel
            {
                Sneakers = allSneakers.Select(x => new SneakerDetailInfo
                {
                    Description = x.Description,
                    Id = x.Id,
                    Name = x.Name,
                    Price = x.Price,
                    ImageSource = "images/" + x.ImageName,
                }).ToArray(),
                TotalCount = allSneakers.Count(),
            });
        }

        
    }
}

2020-2021/informatic/SemestrWork/SemestrovkaV2/SemestrovkaV2/SemestrovkaV2/Controllers/SneakerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SemestrovkaV2.DataAccess.Abstract;
using SemestrovkaV2.DbModels;
using SemestrovkaV2.Models;
using System.Collections.Generic;
using System.Linq;

namespace SemestrovkaV2.Controllers
{
    public class SneakerController : Controller
    {
        private readonly ISneakerRepository sneakerRepository;
        private readonly IUserRepository userRepository;
        private readonly IFeedbackRepository feedbackRepository;

        public SneakerController(ISneakerRepository sneakerRepository, IFeedbackRepository feedbackRepository, IUserRepository userRepository)
        {
            this.sneakerRepository = sneakerRepository;
            this.feedbackRepository = feedbackRepository;
            this.userRepository = userRepository;
        }

        [HttpGet]
        public IActionResult SneakerInfo(int id)
        {
            Sneaker s = sneakerRepository.FindById(id);
            if (s != null)
            {
                var sneaker = SneakerDetailInfo.SneakerFromDbModel(s);

                IEnumerable<Feedback> feedbacksFromDB = feedbackRepository.AllBySneakerId(id);

                return View(new SneakerView
                {
                    Sneaker = sneaker,
                    Feedbacks = FeedbackModel.GetFeedbackModelsFromDBModels(feedbacksFromDB).ToList(),
                });
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Authorize]
        public IActionResult PostFeedback(string text, int id)
        {
            var emailClaim = User.Claims.First(x => x.Type == "Email");
            var emailValue = emailClaim.Value;
            var user = this.userRepository.FindByEmail(emailValue);

            Feedback feedback = new Feedback
            {
                AuthorId = user.Id,
                AuthorName = user.FirstName + ' ' + user.LastName,
                FeedbackText = text,
                SneakerId = id
            };

            feedbackRepository.Save(feedback);
            return RedirectToAction("SneakerInfo", new { id = id });
        }
    }
}

2020-2021/informatic/SemestrWork/SemestrovkaV2/SemestrovkaV2/SemestrovkaV2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

2020-2021/informatic/SemestrWork/SemestrovkaV2/SemestrovkaV2/SemestrovkaV2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

2020-2021/informatic/SemestrWork/SemestrovkaV2/SemestrovkaV2/SemestrovkaV2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model SneakerListViewModel

<table class="table">
    <thead>
        <tr>
            <th>
                <span>Id</span>
            </th>
            <th>
                <span>Image</span>
            </th>
            <th>
                <span>Name</span>
            </th>
            <th>
                <span>Description</span>
            </th>
            <th>
                <span>Price</span>
            </th>
            <th>
                <span>Add to cart</span>
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Sneakers.Length; i++)
        {
            <tr>
                <td>
                    <span>@Model.Sneakers[i].Id</span>
                </td>
                <td>
                    <a asp-action="SneakerInfo" asp-controller="Sneaker" asp-route-id="@Model.Sneakers[i].Id"><img src="@Model.Sneakers[i].ImageSource" alt="Sneaker" style="max-width: 256px;" /></a>
                </td>
                <td>
                    <span>@Model.Sneakers[i].Name</span>
                </td>
                <td>
                    <span>@Model.Sneakers[i].Description</span>
                </td>
                <td>
                    <span>@Model.Sneakers[i].Price</span>
                </td>
                <td>
                    <form asp-action="AddToCart" asp-controller="Cart" method="post">
                        <input type="hidden" name="id" value="@Model.Sneakers[i].Id" />
                        <input type="submit" class="btn btn-primary" value="Add to cart" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>